# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction-analyzer-db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# sql
  sql:
    init:
      mode: never

# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

# h2
  h2:
    console:
      enabled: true
      path: /h2-console

# Tamanho de arquivo suportado  
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB

# Ativando hidden methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
# Mail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

