# datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transaction-analyzer-db
    username: sa
    password: 

# sql
  sql:
    init:
      mode: always

# jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

# h2
  h2:
    console:
      enabled: true
      path: /h2-console

# Tamanho de arquivo suportado  
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB

# Ativando hidden methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

