# datasource
spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}

# sql
  sql:
    init:
      mode: never

# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

# Tamanho de arquivo suportado  
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB

# Ativando hidden methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
# Mail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

# enable errors while binding
server:
  error:
    include-binding-errors: always